#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Print the message.
cat <<-EOF

All your base are belong to us....
    You have no chance to survive make your time.
     -CATS
EOF

